function exportPaperFigure(fig, outputBase)
%EXPORTPAPERFIGURE Export a formatted paper figure as PDF and PNG.
%   EXPORTPAPERFIGURE(FIG, OUTPUTBASE) writes a vector PDF for LaTeX and a
%   300-dpi PNG preview. OUTPUTBASE should not include a file extension.

    arguments
        fig (1,1) matlab.ui.Figure
        outputBase {mustBeTextScalar}
    end

    outputBase = string(outputBase);
    [outputDir, outputName, ~] = fileparts(outputBase);
    if strlength(outputDir) == 0
        outputDir = ".";
    end
    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end

    outputBase = fullfile(outputDir, outputName);
    drawnow;

    originalUnits = fig.Units;
    fig.Units = 'centimeters';
    figureWidth_cm = fig.Position(3);
    figureHeight_cm = fig.Position(4);

    exportgraphics(fig, outputBase + ".pdf", ...
        'ContentType', 'vector', ...
        'Resolution', 300, ...
        'BackgroundColor', 'white', ...
        'Width', figureWidth_cm, ...
        'Height', figureHeight_cm, ...
        'Units', 'centimeters', ...
        'Padding', 'figure', ...
        'PreserveAspectRatio', 'off');
    exportgraphics(fig, outputBase + ".png", ...
        'Resolution', 300, ...
        'BackgroundColor', 'white', ...
        'Width', figureWidth_cm, ...
        'Height', figureHeight_cm, ...
        'Units', 'centimeters', ...
        'Padding', 'figure', ...
        'PreserveAspectRatio', 'off');

    fig.Units = originalUnits;
end
